import subprocess
from pathlib import Path


class UmbraTaskExecutor:
    """
    Executes real system-level or file-level actions.
    """

    def __init__(self, base_path="C:\\Umbra"):
        self.base_path = Path(base_path)

    def execute_step(self, step: str, context=None):
        """
        Executes a step safely.
        """

        context = context or {}

        # SIMPLE ROUTING LAYER (expandable)

        # file creation
        if step.startswith("create file"):
            return self._create_file(step)

        # run command
        if step.startswith("run"):
            return self._run_command(step)

        # default: log-only execution
        return {"status": "logged", "step": step}

    def _create_file(self, step: str):
        try:
            _, path = step.split(":", 1)
            file_path = self.base_path / path.strip()
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text("# generated by Umbra\n", encoding="utf-8")

            return {"status": "file_created", "path": str(file_path)}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def _run_command(self, step: str):
        try:
            cmd = step.replace("run", "").strip()
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            return {
                "status": "executed",
                "stdout": result.stdout[-1000:],
                "stderr": result.stderr[-1000:]
            }
        except Exception as e:
            return {"status": "error", "error": str(e)}