"""
DemiWorldT — Open World RPG
Generated by Umbra Deep Build
Controls: WASD=move, Shift=sprint, I=inventory, Q=quests, E=interact,
          C=crouch, ESC=pause, F5=save, F9=load, Click=attack
"""
import pygame
import sys
import math
import random
import json
import os
import time as _time

pygame.init()

# ── Constants ─────────────────────────────────────────────────────────────────
SW, SH = 1280, 720
TILE = 32
MAP_W, MAP_H = 200, 200
FPS = 60
SAVE_FILE = os.path.join(os.path.dirname(__file__), "demiworld_save.json")

# Colours
BLACK  = (0,0,0);      WHITE   = (255,255,255); GRAY   = (120,120,120)
DKGRAY = (40,40,40);   LTGRAY  = (200,200,200); RED    = (200,40,40)
GREEN  = (40,180,40);  BLUE    = (40,80,200);   CYAN   = (40,200,200)
YELLOW = (220,200,40); ORANGE  = (220,120,40);  PURPLE = (140,40,200)
BROWN  = (120,80,40);  DKGRN   = (20,100,20);   TAN    = (180,150,100)
GOLD   = (255,215,0);  PINK    = (220,100,150);  TEAL  = (20,160,140)
MAROON = (120,20,20);  NAVY    = (20,20,120);    DKRED = (140,20,20)

# Biome tile colours
BIOME_COL = {
    "plains":   (80,160,60),
    "forest":   (30,100,30),
    "mountain": (130,110,90),
    "desert":   (210,190,120),
    "water":    (40,80,180),
    "snow":     (220,230,240),
    "swamp":    (60,90,50),
    "road":     (160,140,100),
    "town":     (170,130,80),
    "camp":     (140,80,50),
    "mine":     (100,90,80),
    "wood_area":(50,120,50),
}

# States
ST_MENU=0; ST_CLASS=1; ST_PLAY=2; ST_INV=3; ST_QUEST=4
ST_DIAL=5; ST_SHOP=6; ST_CRAFT=7; ST_PAUSE=8; ST_CITY=9
ST_GAMEOVER=10; ST_MAP=11

# ── World Generation ──────────────────────────────────────────────────────────
def gen_world():
    wmap = [["plains"]*MAP_W for _ in range(MAP_H)]
    rng = random.Random(42)

    def fill(cx,cy,rad,btype,n=1):
        for _ in range(n):
            ox,oy = rng.randint(-20,20), rng.randint(-20,20)
            for dy in range(-rad,rad+1):
                for dx in range(-rad,rad+1):
                    if dx*dx+dy*dy <= rad*rad:
                        x2,y2 = cx+ox+dx, cy+oy+dy
                        if 0<=x2<MAP_W and 0<=y2<MAP_H:
                            wmap[y2][x2] = btype

    # Biomes
    fill(30,30,25,"forest"); fill(80,50,20,"forest"); fill(150,30,22,"forest")
    fill(170,170,18,"forest"); fill(60,160,20,"forest")
    fill(100,100,30,"mountain"); fill(160,80,15,"mountain"); fill(40,130,12,"mountain")
    fill(180,50,18,"desert"); fill(150,160,22,"desert"); fill(10,80,14,"desert")
    fill(90,170,12,"swamp"); fill(170,130,10,"swamp")
    fill(20,20,8,"water"); fill(110,50,6,"water"); fill(50,100,5,"water")
    fill(180,180,8,"snow"); fill(10,170,6,"snow")

    # Towns (3) + Cities (2)
    towns = [(50,50,"Stonehaven"),(130,140,"Rivergate"),(80,90,"Duskmill")]
    cities = [(100,40,"Ironhold"),(160,110,"Goldenspire")]
    for tx,ty,_ in towns:
        for dy in range(-6,7):
            for dx in range(-6,7):
                if abs(dx)+abs(dy)<8 and 0<=tx+dx<MAP_W and 0<=ty+dy<MAP_H:
                    wmap[ty+dy][tx+dx]="town"
    for cx2,cy2,_ in cities:
        for dy in range(-9,10):
            for dx in range(-9,10):
                if abs(dx)+abs(dy)<11 and 0<=cx2+dx<MAP_W and 0<=cy2+dy<MAP_H:
                    wmap[cy2+dy][cx2+dx]="town"

    # Camps + resource areas
    bandit_camps = [(30,70),(140,60),(90,120)]
    goblin_camps = [(60,140),(120,80),(170,150)]
    mines = [(110,95),(155,75),(35,125)]
    woodcuts = [(55,45),(135,145),(75,85)]

    for bx,by in bandit_camps:
        fill(bx,by,5,"camp",1)
    for gx,gy in goblin_camps:
        fill(gx,gy,4,"camp",1)
    for mx,my in mines:
        fill(mx,my,4,"mine",1)
    for wx,wy in woodcuts:
        fill(wx,wy,4,"wood_area",1)

    return wmap, towns, cities, bandit_camps, goblin_camps, mines, woodcuts

WORLD_MAP, TOWNS, CITIES, BANDIT_CAMPS, GOBLIN_CAMPS, MINES, WOODCUTS = gen_world()

# ── Data Tables ───────────────────────────────────────────────────────────────
WEAPONS = [
    {"name":"Iron Sword",     "atk":12, "type":"melee",  "val":80,  "mat":"iron ore","qty":3},
    {"name":"Steel Axe",      "atk":16, "type":"melee",  "val":150, "mat":"steel",   "qty":3},
    {"name":"Shadow Dagger",  "atk":10, "type":"melee",  "val":120, "mat":"leather", "qty":2},
    {"name":"Oak Bow",        "atk":14, "type":"ranged", "val":100, "mat":"wood",    "qty":5},
    {"name":"Flame Staff",    "atk":20, "type":"magic",  "val":200, "mat":"magic crystal","qty":2},
    {"name":"Frost Wand",     "atk":18, "type":"magic",  "val":180, "mat":"magic crystal","qty":2},
    {"name":"Battle Hammer",  "atk":22, "type":"melee",  "val":220, "mat":"steel",   "qty":4},
    {"name":"Silver Spear",   "atk":17, "type":"melee",  "val":160, "mat":"steel",   "qty":3},
    {"name":"Throwing Stars", "atk":8,  "type":"ranged", "val":60,  "mat":"iron ore","qty":10},
    {"name":"Death Scythe",   "atk":28, "type":"melee",  "val":350, "mat":"bone",    "qty":5},
]
ARMOR_SETS = [
    {"name":"Iron Set",   "parts":["Iron Helm","Iron Chest","Iron Legs"],   "def":8,  "val":200, "mat":"iron ore","qty":5},
    {"name":"Steel Set",  "parts":["Steel Helm","Steel Chest","Steel Legs"],"def":16, "val":400, "mat":"steel",   "qty":6},
    {"name":"Shadow Set", "parts":["Shadow Hood","Shadow Coat","Shadow Boots"],"def":12,"val":300,"mat":"leather","qty":4},
]
SPELLS = [
    {"name":"Fireball",    "mp":20, "dmg":30, "col":RED,    "desc":"Launches a fireball"},
    {"name":"Ice Spike",   "mp":18, "dmg":25, "col":CYAN,   "desc":"Fires a spike of ice"},
    {"name":"Lightning",   "mp":25, "dmg":35, "col":YELLOW, "desc":"Strikes with lightning"},
    {"name":"Heal",        "mp":15, "dmg":-30,"col":GREEN,  "desc":"Restores HP"},
    {"name":"Shield",      "mp":20, "dmg":0,  "col":BLUE,   "desc":"Raises magic shield"},
    {"name":"Teleport",    "mp":30, "dmg":0,  "col":PURPLE, "desc":"Teleports short distance"},
    {"name":"Summon Wolf", "mp":40, "dmg":0,  "col":GRAY,   "desc":"Summons a wolf ally"},
    {"name":"Earthquake",  "mp":50, "dmg":45, "col":BROWN,  "desc":"Shakes the earth"},
    {"name":"Drain Life",  "mp":22, "dmg":20, "col":MAROON, "desc":"Drains enemy life"},
    {"name":"Time Slow",   "mp":35, "dmg":0,  "col":TEAL,   "desc":"Slows time briefly"},
]
MATERIALS = ["wood","stone","iron ore","steel","leather","magic crystal","bone","arrow","dart","herb"]

ENEMY_DEFS = [
    {"name":"Goblin",      "hp":30,  "atk":6,  "def":2,  "xp":15,  "col":GREEN,  "spd":2.0, "faction":"goblin"},
    {"name":"Bandit",      "hp":50,  "atk":10, "def":4,  "xp":25,  "col":ORANGE, "spd":1.8, "faction":"bandit"},
    {"name":"Orc",         "hp":80,  "atk":15, "def":8,  "xp":40,  "col":DKGRN,  "spd":1.2, "faction":"goblin"},
    {"name":"Skeleton",    "hp":45,  "atk":12, "def":6,  "xp":30,  "col":LTGRAY, "spd":1.5, "faction":"undead"},
    {"name":"Wolf",        "hp":35,  "atk":9,  "def":3,  "xp":20,  "col":GRAY,   "spd":2.5, "faction":"wild"},
    {"name":"Dark Mage",   "hp":60,  "atk":20, "def":5,  "xp":50,  "col":PURPLE, "spd":1.4, "faction":"undead"},
    {"name":"Troll",       "hp":120, "atk":18, "def":12, "xp":70,  "col":DKGRN,  "spd":0.9, "faction":"wild"},
    {"name":"Spider",      "hp":25,  "atk":8,  "def":2,  "xp":18,  "col":BLACK,  "spd":2.2, "faction":"wild"},
    {"name":"Dragon Spawn","hp":150, "atk":25, "def":15, "xp":100, "col":RED,    "spd":1.6, "faction":"dragon"},
    {"name":"Mimic",       "hp":70,  "atk":16, "def":10, "xp":60,  "col":BROWN,  "spd":1.0, "faction":"wild"},
]

NPC_NAMES = ["Aldric","Brynn","Cael","Dova","Eryn","Fenn","Gara","Holt",
             "Isla","Jorn","Kira","Lonn","Mira","Nael","Orra","Pell"]
NPC_JOBS  = ["Merchant","Farmer","Miner","Woodcutter","Guard","Blacksmith",
             "Alchemist","Fisher","Baker","Innkeeper"]

QUESTS = [
    {"id":"q1","name":"First Blood",    "desc":"Kill 3 Goblins",   "target":"Goblin",  "need":3,  "prog":0, "done":False, "reward_gold":100,"reward_xp":50},
    {"id":"q2","name":"Bandit Bane",    "desc":"Kill 5 Bandits",   "target":"Bandit",  "need":5,  "prog":0, "done":False, "reward_gold":200,"reward_xp":100},
    {"id":"q3","name":"Wolf Hunt",      "desc":"Kill 4 Wolves",    "target":"Wolf",    "need":4,  "prog":0, "done":False, "reward_gold":150,"reward_xp":75},
    {"id":"q4","name":"Ore Collector",  "desc":"Collect 10 iron ore","target":"mat:iron ore","need":10,"prog":0,"done":False,"reward_gold":80,"reward_xp":40},
    {"id":"q5","name":"Lumber Run",     "desc":"Collect 10 wood",  "target":"mat:wood","need":10,"prog":0,"done":False,"reward_gold":80,"reward_xp":40},
]

FACTIONS = {
    "kingdom": {"rep":0,"name":"The Kingdom"},
    "bandit":  {"rep":0,"name":"Bandit Clan"},
    "goblin":  {"rep":0,"name":"Goblin Horde"},
}

DIALOGUE_TREES = {
    "Merchant": [
        {"text":"Greetings, traveller! I have fine wares.","opts":["Browse shop","Ask about town","Goodbye"]},
        {"text":"The town has seen better days — bandits everywhere.","opts":["Goodbye"]},
    ],
    "Guard": [
        {"text":"Halt! State your business in this town.","opts":["I'm a traveller","I seek work","Goodbye"]},
        {"text":"There's work if you want it — clear the bandit camp north of here.","opts":["Accept quest","Goodbye"]},
    ],
    "default": [
        {"text":"Hello there, stranger.","opts":["What's new?","Goodbye"]},
        {"text":"Not much to say, I'm afraid.","opts":["Goodbye"]},
    ],
}

# ── Helper: draw text ─────────────────────────────────────────────────────────
_font_cache = {}
def font(size):
    if size not in _font_cache:
        _font_cache[size] = pygame.font.SysFont("segoeui", size)
    return _font_cache[size]

def txt(surf, text, x, y, size=16, col=WHITE, center=False):
    f = font(size)
    s = f.render(str(text), True, col)
    if center:
        x -= s.get_width()//2
    surf.blit(s, (x,y))
    return s.get_width(), s.get_height()

def draw_bar(surf, x, y, w, h, val, mx, col, bg=DKGRAY):
    pygame.draw.rect(surf, bg, (x,y,w,h))
    fill = int(w * max(0, val/max(mx,1)))
    if fill > 0:
        pygame.draw.rect(surf, col, (x,y,fill,h))
    pygame.draw.rect(surf, GRAY, (x,y,w,h), 1)

def draw_x_button(surf, rx, ry, rw, rh, col=WHITE):
    """Draw an X close button in top-right of rect. Returns button rect."""
    btn = pygame.Rect(rx+rw-26, ry+4, 22, 22)
    pygame.draw.rect(surf, DKRED, btn, border_radius=4)
    pygame.draw.line(surf, WHITE, (btn.x+4, btn.y+4), (btn.right-4, btn.bottom-4), 2)
    pygame.draw.line(surf, WHITE, (btn.right-4, btn.y+4), (btn.x+4, btn.bottom-4), 2)
    return btn

def draw_panel(surf, rx, ry, rw, rh, title="", alpha=220):
    s = pygame.Surface((rw,rh), pygame.SRCALPHA)
    s.fill((20,20,30,alpha))
    surf.blit(s, (rx,ry))
    pygame.draw.rect(surf, (80,80,120), (rx,ry,rw,rh), 2, border_radius=6)
    if title:
        txt(surf, title, rx+10, ry+8, 18, GOLD)
    return draw_x_button(surf, rx, ry, rw, rh)

# ── Entity classes ─────────────────────────────────────────────────────────────
class Entity:
    def __init__(self, x, y, col, size=16):
        self.x = float(x*TILE + TILE//2)
        self.y = float(y*TILE + TILE//2)
        self.col = col
        self.size = size
        self.vx = self.vy = 0.0

    def draw(self, surf, cam_x, cam_y):
        sx = int(self.x - cam_x)
        sy = int(self.y - cam_y)
        if -self.size*2 <= sx <= SW+self.size*2 and -self.size*2 <= sy <= SH+self.size*2:
            pygame.draw.circle(surf, self.col, (sx,sy), self.size)

    @property
    def tile_x(self): return int(self.x // TILE)
    @property
    def tile_y(self): return int(self.y // TILE)


class Player(Entity):
    def __init__(self, cls="Warrior"):
        super().__init__(50, 50, BLUE, 14)
        self.cls = cls
        base = {"Warrior":{"hp":120,"mp":40,"str":14,"dex":8,"int":6},
                "Mage":   {"hp":70, "mp":120,"str":6, "dex":8,"int":16},
                "Rogue":  {"hp":90, "mp":60, "str":10,"dex":16,"int":8}}[cls]
        self.max_hp=base["hp"]; self.hp=self.max_hp
        self.max_mp=base["mp"]; self.mp=self.max_mp
        self.max_sta=100;       self.sta=100
        self.str_=base["str"]; self.dex=base["dex"]; self.int_=base["int"]
        self.luck=5; self.level=1; self.xp=0; self.xp_next=100
        self.gold=200; self.speed=3.0
        self.inventory={}   # name->qty
        self.equipped={"weapon":None,"armor":None}
        self.spells=[]
        self.quests=[dict(q) for q in QUESTS]
        self.faction_rep=dict(FACTIONS)
        self.squad=[]
        self.crouching=False
        self.regen_timer=0
        # add starter gear
        self.inventory["Iron Sword"]=1
        self.inventory["Iron Chest"]=1
        self.inventory["wood"]=5
        self.inventory["iron ore"]=5
        self.inventory["herb"]=3
        self.spells.append(dict(SPELLS[0]))  # Fireball
        self.equipped["weapon"]="Iron Sword"
        self.equipped["armor"]="Iron Chest"

    def gain_xp(self, amt):
        self.xp += amt
        while self.xp >= self.xp_next:
            self.xp -= self.xp_next
            self.level += 1
            self.xp_next = int(self.xp_next*1.4)
            self.max_hp += 10; self.hp = min(self.hp+20, self.max_hp)
            self.max_mp += 5;  self.mp = min(self.mp+10, self.max_mp)
            self.str_ += 1; self.dex += 1; self.int_ += 1
            return True
        return False

    def atk_power(self):
        base = self.str_
        if self.equipped["weapon"]:
            w = next((w for w in WEAPONS if w["name"]==self.equipped["weapon"]),None)
            if w: base += w["atk"]
        return base

    def def_power(self):
        base = self.dex // 3
        if self.equipped["armor"]:
            for aset in ARMOR_SETS:
                if self.equipped["armor"] in aset["parts"]:
                    base += aset["def"]
                    break
        return base

    def add_item(self, name, qty=1):
        self.inventory[name] = self.inventory.get(name,0)+qty
        # Quest progress for materials
        for q in self.quests:
            if not q["done"] and q["target"] == "mat:"+name:
                q["prog"] = min(q["prog"]+qty, q["need"])

    def regen(self, dt):
        self.regen_timer += dt
        if self.regen_timer > 3.0:
            self.regen_timer = 0
            self.hp  = min(self.hp+2,  self.max_hp)
            self.mp  = min(self.mp+3,  self.max_mp)
            self.sta = min(self.sta+5, self.max_sta)


class Enemy(Entity):
    def __init__(self, edef, tx, ty):
        col = edef.get("col", RED)
        super().__init__(tx, ty, col, 12)
        self.edef   = edef
        self.name   = edef["name"]
        self.max_hp = edef["hp"] + random.randint(-5,10)
        self.hp     = self.max_hp
        self.atk    = edef["atk"]
        self.defense= edef["def"]
        self.xp_val = edef["xp"]
        self.spd    = edef.get("spd", 1.5)
        self.faction= edef.get("faction","wild")
        self.aggro  = False
        self.atk_cd = 0.0
        self.loot   = random.choice(MATERIALS) if random.random()<0.5 else None

    def update(self, player, dt):
        dx = player.x - self.x
        dy = player.y - self.y
        dist = math.hypot(dx,dy)
        if dist < 250: self.aggro = True
        if dist > 400: self.aggro = False
        if self.aggro and dist > 20:
            norm = max(dist,1)
            self.x += (dx/norm)*self.spd*dt*60
            self.y += (dy/norm)*self.spd*dt*60
        self.atk_cd = max(0, self.atk_cd-dt)

    def draw(self, surf, cam_x, cam_y):
        super().draw(surf, cam_x, cam_y)
        sx = int(self.x-cam_x); sy = int(self.y-cam_y)
        if 0<=sx<=SW and 0<=sy<=SH:
            draw_bar(surf, sx-16, sy-22, 32, 5, self.hp, self.max_hp, RED)
            txt(surf, self.name, sx, sy-32, 11, WHITE, center=True)


class NPC(Entity):
    def __init__(self, name, job, tx, ty):
        col_map={"Merchant":GOLD,"Guard":BLUE,"Farmer":GREEN,
                 "Miner":GRAY,"Blacksmith":ORANGE,"default":TAN}
        super().__init__(tx, ty, col_map.get(job, TAN), 12)
        self.name=name; self.job=job
        self.dialogue=DIALOGUE_TREES.get(job, DIALOGUE_TREES["default"])
        self.dial_idx=0
        self.shop_stock={}
        if job=="Merchant":
            for w in random.sample(WEAPONS,3):
                self.shop_stock[w["name"]]={"price":w["val"],"qty":5}
            for m in random.sample(MATERIALS,4):
                self.shop_stock[m]={"price":random.randint(5,30),"qty":20}

    def draw(self, surf, cam_x, cam_y):
        super().draw(surf, cam_x, cam_y)
        sx=int(self.x-cam_x); sy=int(self.y-cam_y)
        if 0<=sx<=SW and 0<=sy<=SH:
            txt(surf, self.name, sx, sy-28, 11, YELLOW, center=True)
            txt(surf, self.job, sx, sy-18, 10, LTGRAY, center=True)


class Projectile:
    def __init__(self, x, y, tx, ty, dmg, col, speed=8):
        self.x=float(x); self.y=float(y)
        d=math.hypot(tx-x,ty-y) or 1
        self.vx=(tx-x)/d*speed; self.vy=(ty-y)/d*speed
        self.dmg=dmg; self.col=col; self.alive=True
        self.life=120

    def update(self):
        self.x+=self.vx; self.y+=self.vy
        self.life-=1
        if self.life<=0: self.alive=False

    def draw(self, surf, cam_x, cam_y):
        pygame.draw.circle(surf, self.col, (int(self.x-cam_x),int(self.y-cam_y)), 5)


class Building:
    TYPES={
        "House":    {"col":BROWN,  "w":3,"h":3,"cost":{"wood":10,"stone":5}},
        "Shop":     {"col":ORANGE, "w":4,"h":3,"cost":{"wood":15,"stone":10}},
        "Barracks": {"col":NAVY,   "w":5,"h":4,"cost":{"wood":20,"stone":15,"iron ore":5}},
        "Farm":     {"col":GREEN,  "w":4,"h":4,"cost":{"wood":8, "stone":0}},
        "Tower":    {"col":GRAY,   "w":2,"h":5,"cost":{"stone":20,"iron ore":10}},
        "Warehouse":{"col":TAN,    "w":5,"h":4,"cost":{"wood":25,"stone":10}},
    }
    def __init__(self, btype, tx, ty):
        self.btype=btype; self.tx=tx; self.ty=ty
        d=self.TYPES[btype]
        self.col=d["col"]; self.bw=d["w"]; self.bh=d["h"]
        self.cost=d["cost"]; self.npcs=[]

    def draw(self, surf, cam_x, cam_y):
        sx=self.tx*TILE-cam_x; sy=self.ty*TILE-cam_y
        pw=self.bw*TILE; ph=self.bh*TILE
        pygame.draw.rect(surf, self.col, (sx,sy,pw,ph))
        pygame.draw.rect(surf, WHITE, (sx,sy,pw,ph), 2)
        txt(surf, self.btype, sx+pw//2, sy+ph//2-8, 12, WHITE, center=True)


# ── Camera ────────────────────────────────────────────────────────────────────
class Camera:
    def __init__(self):
        self.x=0.0; self.y=0.0
    def update(self, player):
        tx = player.x - SW//2
        ty = player.y - SH//2
        max_x = MAP_W*TILE - SW; max_y = MAP_H*TILE - SH
        self.x += (max(0,min(tx,max_x)) - self.x)*0.12
        self.y += (max(0,min(ty,max_y)) - self.y)*0.12


# ── Floating text ─────────────────────────────────────────────────────────────
class FloatText:
    def __init__(self, text, x, y, col=WHITE):
        self.text=text; self.x=float(x); self.y=float(y)
        self.col=col; self.life=80; self.max_life=80
    def update(self): self.y-=0.8; self.life-=1
    def draw(self, surf, cam_x, cam_y):
        alpha = int(255*(self.life/self.max_life))
        f=font(15)
        s=f.render(self.text,True,self.col)
        s.set_alpha(alpha)
        surf.blit(s,(int(self.x-cam_x)-s.get_width()//2,int(self.y-cam_y)))


# ── World spawn ───────────────────────────────────────────────────────────────
def spawn_world_entities():
    enemies=[]; npcs=[]; buildings=[]
    rng=random.Random(99)

    # Bandits at bandit camps
    for bx,by in BANDIT_CAMPS:
        for _ in range(4):
            ex=bx+rng.randint(-4,4); ey=by+rng.randint(-4,4)
            enemies.append(Enemy(ENEMY_DEFS[1], ex, ey))  # Bandit

    # Goblins at goblin camps
    for gx,gy in GOBLIN_CAMPS:
        for _ in range(4):
            ex=gx+rng.randint(-3,3); ey=gy+rng.randint(-3,3)
            enemies.append(Enemy(ENEMY_DEFS[0], ex, ey))  # Goblin
        # Add an Orc leader
        enemies.append(Enemy(ENEMY_DEFS[2], gx, gy))

    # Random enemies in wilderness
    WILD=[ENEMY_DEFS[3],ENEMY_DEFS[4],ENEMY_DEFS[6],ENEMY_DEFS[7]]
    for _ in range(30):
        ex=rng.randint(5,MAP_W-5); ey=rng.randint(5,MAP_H-5)
        if WORLD_MAP[ey][ex] not in ("town","water"):
            enemies.append(Enemy(rng.choice(WILD), ex, ey))

    # NPCs in towns
    all_locs=TOWNS+[(cx,cy,nm) for cx,cy,nm in CITIES]
    for tx,ty,_ in all_locs:
        for job in ["Merchant","Guard","Guard","Farmer","Farmer","Miner","Blacksmith"]:
            nx=tx+rng.randint(-4,4); ny=ty+rng.randint(-4,4)
            name=rng.choice(NPC_NAMES)
            npcs.append(NPC(name, job, nx, ny))

    return enemies, npcs, buildings


# ── Tile renderer ─────────────────────────────────────────────────────────────
TILE_SURF_CACHE={}
def get_tile_surf(btype):
    if btype not in TILE_SURF_CACHE:
        s=pygame.Surface((TILE,TILE))
        col=BIOME_COL.get(btype,(100,100,100))
        s.fill(col)
        # Add texture variation
        if btype=="forest":
            for _ in range(4):
                rx=random.randint(2,TILE-6); ry=random.randint(2,TILE-6)
                pygame.draw.circle(s,(20,80,20),(rx,ry),3)
        elif btype=="mountain":
            pygame.draw.polygon(s,(160,140,120),[(TILE//2,4),(4,TILE-4),(TILE-4,TILE-4)])
        elif btype=="water":
            pygame.draw.line(s,(60,100,200),(2,TILE//2),(TILE-2,TILE//2),2)
        elif btype=="mine":
            pygame.draw.rect(s,(80,70,60),(6,6,TILE-12,TILE-12))
        elif btype=="wood_area":
            pygame.draw.rect(s,(40,100,40),(8,8,TILE-16,TILE-16))
        TILE_SURF_CACHE[btype]=s
    return TILE_SURF_CACHE[btype]


def draw_world(surf, cam_x, cam_y):
    tx0=max(0,int(cam_x//TILE)); ty0=max(0,int(cam_y//TILE))
    tx1=min(MAP_W, tx0+SW//TILE+2); ty1=min(MAP_H, ty0+SH//TILE+2)
    for ty in range(ty0,ty1):
        for tx in range(tx0,tx1):
            btype=WORLD_MAP[ty][tx]
            s=get_tile_surf(btype)
            surf.blit(s,(tx*TILE-int(cam_x), ty*TILE-int(cam_y)))


# ── UI Screens ────────────────────────────────────────────────────────────────
def draw_hud(surf, player):
    # Bars
    draw_bar(surf,10,SH-70,160,16,player.hp,player.max_hp,RED)
    txt(surf,f"HP {player.hp}/{player.max_hp}",14,SH-70,12)
    draw_bar(surf,10,SH-50,160,16,player.mp,player.max_mp,BLUE)
    txt(surf,f"MP {player.mp}/{player.max_mp}",14,SH-50,12)
    draw_bar(surf,10,SH-30,160,16,player.sta,player.max_sta,YELLOW)
    txt(surf,f"STA {int(player.sta)}/100",14,SH-30,12)
    # XP
    draw_bar(surf,180,SH-30,200,12,player.xp,player.xp_next,(100,200,255))
    txt(surf,f"Lv{player.level}",182,SH-46,13,GOLD)
    txt(surf,f"{player.xp}/{player.xp_next} XP",184,SH-30,11)
    # Gold
    txt(surf,f"Gold: {player.gold}",SW-120,SH-30,15,GOLD)
    # Equipped
    txt(surf,f"W: {player.equipped['weapon'] or 'None'}",SW-200,SH-70,13,LTGRAY)
    txt(surf,f"A: {player.equipped['armor'] or 'None'}",SW-200,SH-52,13,LTGRAY)
    # Crouch
    if player.crouching:
        txt(surf,"[CROUCHING]",SW//2-40,SH-28,14,CYAN)


def draw_minimap(surf, player, enemies):
    MX=SW-130; MY=10; MW=120; MH=120
    pygame.draw.rect(surf,(20,20,40),(MX,MY,MW,MH))
    pygame.draw.rect(surf,GRAY,(MX,MY,MW,MH),2)
    # World tiles (downsampled)
    scale_x=MW/MAP_W; scale_y=MH/MAP_H
    for ty in range(0,MAP_H,2):
        for tx in range(0,MAP_W,2):
            col=BIOME_COL.get(WORLD_MAP[ty][tx],(80,80,80))
            sx=MX+int(tx*scale_x); sy=MY+int(ty*scale_y)
            surf.set_at((sx,sy),col)
    # Player
    px=MX+int(player.tile_x*scale_x); py=MY+int(player.tile_y*scale_y)
    pygame.draw.circle(surf,WHITE,(px,py),3)
    # Enemies
    for e in enemies[:50]:
        ex=MX+int(e.tile_x*scale_x); ey=MY+int(e.tile_y*scale_y)
        if MX<=ex<=MX+MW and MY<=ey<=MY+MH:
            surf.set_at((ex,ey),RED)
    txt(surf,"MAP",MX+MW//2,MY+MH+2,11,GRAY,center=True)


def draw_inventory(surf, player, selected_slot, click_pos=None):
    PX,PY,PW,PH = 60,60,SW-120,SH-120
    xbtn = draw_panel(surf,PX,PY,PW,PH,"Inventory")

    items = list(player.inventory.items())
    COLS=6; SLOT=60
    btns={}
    for i,(name,qty) in enumerate(items):
        col=i//COLS; row=i%COLS
        sx=PX+20+row*SLOT; sy=PY+40+col*SLOT
        is_sel=(i==selected_slot)
        pygame.draw.rect(surf,(60,60,90) if is_sel else (40,40,60),(sx,sy,54,54),border_radius=4)
        pygame.draw.rect(surf,(120,120,160),(sx,sy,54,54),1,border_radius=4)
        txt(surf,name[:8],sx+3,sy+4,10,WHITE)
        txt(surf,str(qty),sx+38,sy+38,11,YELLOW)
        btns[i]=(sx,sy,54,54)

    # Equip/Use panel at bottom
    if 0<=selected_slot<len(items):
        name,qty=items[selected_slot]
        txt(surf,f"Selected: {name} x{qty}",PX+20,PY+PH-80,14,GOLD)
        # Equip button
        eq_btn=pygame.Rect(PX+20,PY+PH-58,80,28)
        pygame.draw.rect(surf,(60,100,60),eq_btn,border_radius=4)
        txt(surf,"Equip",PX+34,PY+PH-53,14,WHITE)
        # Drop button
        dr_btn=pygame.Rect(PX+110,PY+PH-58,80,28)
        pygame.draw.rect(surf,(100,60,60),dr_btn,border_radius=4)
        txt(surf,"Drop",PX+124,PY+PH-53,14,WHITE)
    else:
        eq_btn=dr_btn=None

    return xbtn, btns, eq_btn, dr_btn


def draw_quest_log(surf, player):
    PX,PY,PW,PH=80,50,SW-160,SH-100
    xbtn=draw_panel(surf,PX,PY,PW,PH,"Quest Log")
    for i,q in enumerate(player.quests):
        y=PY+45+i*60
        col=GREEN if q["done"] else WHITE
        status="DONE" if q["done"] else f"{q['prog']}/{q['need']}"
        txt(surf,q["name"],PX+20,y,16,GOLD)
        txt(surf,q["desc"],PX+20,y+18,13,col)
        txt(surf,f"Progress: {status}  Reward: {q['reward_gold']}g / {q['reward_xp']}xp",PX+20,y+36,12,LTGRAY)
    return xbtn


def draw_shop(surf, npc, player, selected_item, click_pos=None):
    PX,PY,PW,PH=80,50,SW-160,SH-100
    xbtn=draw_panel(surf,PX,PY,PW,PH,f"Shop — {npc.name}")
    txt(surf,f"Your Gold: {player.gold}",PX+PW-180,PY+12,14,GOLD)

    items=list(npc.shop_stock.items())
    btn_rects={}
    for i,(name,info) in enumerate(items):
        y=PY+45+i*38
        bg=(60,60,90) if i==selected_item else (30,30,50)
        pygame.draw.rect(surf,bg,(PX+15,y,PW-30,34),border_radius=4)
        pygame.draw.rect(surf,(80,80,120),(PX+15,y,PW-30,34),1,border_radius=4)
        txt(surf,name,PX+25,y+8,14,WHITE)
        txt(surf,f"{info['price']}g x{info['qty']}",PX+PW-130,y+8,13,GOLD)
        btn=pygame.Rect(PX+PW-90,y+5,70,24)
        pygame.draw.rect(surf,(40,100,40),btn,border_radius=4)
        txt(surf,"Buy",PX+PW-72,y+9,13,WHITE)
        btn_rects[i]=btn

    return xbtn, btn_rects, items


def draw_crafting(surf, player, craft_tab, selected_recipe, click_pos=None):
    PX,PY,PW,PH=60,50,SW-120,SH-100
    xbtn=draw_panel(surf,PX,PY,PW,PH,"Crafting")

    tabs=["Fletching","Blacksmith","Alchemy","Building"]
    tab_btns={}
    for i,tab in enumerate(tabs):
        tbr=pygame.Rect(PX+15+i*120,PY+35,110,28)
        col=(60,80,120) if craft_tab==tab else (30,40,60)
        pygame.draw.rect(surf,col,tbr,border_radius=4)
        txt(surf,tab,tbr.x+8,tbr.y+7,13,WHITE)
        tab_btns[tab]=tbr

    recipes={
        "Fletching":[
            {"name":"Arrow","cost":{"wood":1},"out":{"arrow":10}},
            {"name":"Dart", "cost":{"wood":1,"iron ore":1},"out":{"dart":5}},
            {"name":"Oak Bow","cost":{"wood":5,"leather":2},"out":{"Oak Bow":1}},
        ],
        "Blacksmith":[
            {"name":"Iron Sword","cost":{"iron ore":3},"out":{"Iron Sword":1}},
            {"name":"Steel Axe","cost":{"steel":3},"out":{"Steel Axe":1}},
            {"name":"Iron Helm","cost":{"iron ore":5},"out":{"Iron Helm":1}},
            {"name":"Iron Chest","cost":{"iron ore":8},"out":{"Iron Chest":1}},
            {"name":"Iron Legs","cost":{"iron ore":6},"out":{"Iron Legs":1}},
            {"name":"Battle Hammer","cost":{"steel":4},"out":{"Battle Hammer":1}},
        ],
        "Alchemy":[
            {"name":"Health Potion","cost":{"herb":2},"out":{"Health Potion":1}},
            {"name":"Mana Potion","cost":{"herb":3,"magic crystal":1},"out":{"Mana Potion":1}},
        ],
        "Building":[
            {"name":"House","cost":{"wood":10,"stone":5},"out":{"House Blueprint":1}},
            {"name":"Farm", "cost":{"wood":8},"out":{"Farm Blueprint":1}},
        ],
    }

    cur=recipes.get(craft_tab,[])
    craft_btns={}
    for i,r in enumerate(cur):
        y=PY+80+i*52
        bg=(50,70,50) if i==selected_recipe else (30,40,30)
        pygame.draw.rect(surf,bg,(PX+15,y,PW-30,46),border_radius=4)
        pygame.draw.rect(surf,(80,120,80),(PX+15,y,PW-30,46),1,border_radius=4)
        cost_str=" + ".join(f"{q} {n}" for n,q in r["cost"].items())
        out_str=", ".join(f"{q}x {n}" for n,q in r["out"].items())
        txt(surf,r["name"],PX+25,y+5,14,GOLD)
        txt(surf,f"Cost: {cost_str}",PX+25,y+22,12,LTGRAY)
        txt(surf,f"→ {out_str}",PX+PW-220,y+5,12,GREEN)
        can=all(player.inventory.get(n,0)>=q for n,q in r["cost"].items())
        cbtn=pygame.Rect(PX+PW-100,y+12,80,24)
        pygame.draw.rect(surf,(40,100,40) if can else (60,40,40),cbtn,border_radius=4)
        txt(surf,"Craft",PX+PW-85,y+16,13,WHITE if can else GRAY)
        craft_btns[i]=(cbtn,r)

    return xbtn, tab_btns, craft_btns


def draw_dialogue(surf, npc, dial_idx):
    PX,PY,PW,PH=100,SH-220,SW-200,200
    xbtn=draw_panel(surf,PX,PY,PW,PH,npc.name)
    tree=npc.dialogue
    node=tree[min(dial_idx,len(tree)-1)]
    txt(surf,node["text"],PX+15,PY+40,15,WHITE)
    opt_btns={}
    for i,opt in enumerate(node["opts"]):
        br=pygame.Rect(PX+15,PY+80+i*38,PW-30,30)
        pygame.draw.rect(surf,(40,60,100),br,border_radius=4)
        pygame.draw.rect(surf,(80,100,160),br,1,border_radius=4)
        txt(surf,opt,br.x+10,br.y+8,13,WHITE)
        opt_btns[i]=(br,opt)
    return xbtn, opt_btns


def draw_pause(surf):
    PX,PY,PW,PH=SW//2-160,SH//2-200,320,400
    xbtn=draw_panel(surf,PX,PY,PW,PH,"PAUSED")
    labels=["Resume","Save Game","Load Game","Settings","Main Menu","Quit"]
    btns={}
    for i,lab in enumerate(labels):
        br=pygame.Rect(PX+40,PY+60+i*52,240,40)
        pygame.draw.rect(surf,(50,60,90),br,border_radius=6)
        pygame.draw.rect(surf,(100,120,160),br,1,border_radius=6)
        txt(surf,lab,PX+PW//2,br.y+12,16,WHITE,center=True)
        btns[lab]=br
    return xbtn,btns


def draw_main_menu(surf):
    surf.fill((10,10,30))
    # Starfield
    for _ in range(80):
        sx=random.randint(0,SW); sy=random.randint(0,SH)
        pygame.draw.circle(surf,WHITE,(sx,sy),1)
    txt(surf,"DemiWorldT",SW//2,120,64,GOLD,center=True)
    txt(surf,"An Open World RPG",SW//2,195,22,LTGRAY,center=True)
    btns={}
    for i,(lab,col) in enumerate([("New Game",GREEN),("Load Game",BLUE),("Quit",RED)]):
        br=pygame.Rect(SW//2-120,300+i*70,240,52)
        pygame.draw.rect(surf,col,br,border_radius=8)
        pygame.draw.rect(surf,WHITE,br,2,border_radius=8)
        txt(surf,lab,SW//2,br.y+16,20,WHITE,center=True)
        btns[lab]=br
    txt(surf,"v1.0  |  Built by Umbra",SW//2,SH-24,12,GRAY,center=True)
    return btns


def draw_class_select(surf):
    surf.fill((10,10,30))
    txt(surf,"Choose Your Class",SW//2,80,40,GOLD,center=True)
    classes=[
        ("Warrior","High HP & Strength\nBest melee fighter",RED,(14,8,6,120,40)),
        ("Mage","High MP & Intelligence\nMaster of spells",BLUE,(6,8,16,70,120)),
        ("Rogue","High Dexterity\nStealth & speed",PURPLE,(10,16,8,90,60)),
    ]
    btns={}
    for i,(name,desc,col,stats) in enumerate(classes):
        bx=SW//2-360+i*240; by=200
        pygame.draw.rect(surf,(30,30,60),(bx,by,200,280),border_radius=10)
        pygame.draw.rect(surf,col,(bx,by,200,280),3,border_radius=10)
        pygame.draw.circle(surf,col,(bx+100,by+70),40)
        txt(surf,name,bx+100,by+120,20,col,center=True)
        str_,dex,int_,hp,mp=stats
        for j,(stat,val) in enumerate([("STR",str_),("DEX",dex),("INT",int_),("HP",hp),("MP",mp)]):
            txt(surf,f"{stat}: {val}",bx+20,by+150+j*22,13,LTGRAY)
        br=pygame.Rect(bx+30,by+240,140,36)
        pygame.draw.rect(surf,col,br,border_radius=6)
        txt(surf,"Select",bx+100,br.y+10,16,WHITE,center=True)
        btns[name]=br
    return btns


def draw_city_build(surf, player, buildings, place_type):
    PX,PY,PW,PH=0,0,SW,SH
    # transparent overlay
    s=pygame.Surface((SW,SH),pygame.SRCALPHA); s.fill((0,0,0,120)); surf.blit(s,(0,0))
    xbtn=draw_panel(surf,10,10,260,SH-20,"City Builder")

    btypes=list(Building.TYPES.keys())
    type_btns={}
    for i,bt in enumerate(btypes):
        br=pygame.Rect(20,50+i*55,240,46)
        col=(60,80,120) if place_type==bt else (30,40,60)
        pygame.draw.rect(surf,col,br,border_radius=4)
        d=Building.TYPES[bt]
        cost_str=" ".join(f"{q}{n[:3]}" for n,q in d["cost"].items() if q>0)
        txt(surf,bt,br.x+10,br.y+5,14,GOLD)
        txt(surf,f"Cost: {cost_str}",br.x+10,br.y+24,11,LTGRAY)
        type_btns[bt]=br

    txt(surf,"Click map to place",140,SH-40,13,GRAY,center=True)
    return xbtn, type_btns


def draw_gameover(surf):
    surf.fill((20,0,0))
    txt(surf,"YOU DIED",SW//2,SH//2-80,72,RED,center=True)
    txt(surf,"Press R to respawn or M for Main Menu",SW//2,SH//2+20,20,LTGRAY,center=True)


# ── Save / Load ───────────────────────────────────────────────────────────────
def save_game(player, buildings):
    data={
        "pos":[player.x, player.y],
        "cls":player.cls,
        "hp":player.hp,"mp":player.mp,"sta":player.sta,
        "max_hp":player.max_hp,"max_mp":player.max_mp,
        "level":player.level,"xp":player.xp,"xp_next":player.xp_next,
        "gold":player.gold,
        "str_":player.str_,"dex":player.dex,"int_":player.int_,
        "inventory":player.inventory,
        "equipped":player.equipped,
        "spells":[s["name"] for s in player.spells],
        "quests":player.quests,
        "buildings":[{"type":b.btype,"tx":b.tx,"ty":b.ty} for b in buildings],
    }
    with open(SAVE_FILE,"w") as f:
        json.dump(data,f,indent=2)
    return True

def load_game(player, buildings):
    if not os.path.exists(SAVE_FILE): return False
    try:
        with open(SAVE_FILE) as f: data=json.load(f)
        player.x,player.y=data["pos"]
        player.hp=data["hp"]; player.mp=data["mp"]; player.sta=data["sta"]
        player.max_hp=data["max_hp"]; player.max_mp=data["max_mp"]
        player.level=data["level"]; player.xp=data["xp"]; player.xp_next=data["xp_next"]
        player.gold=data["gold"]
        player.str_=data["str_"]; player.dex=data["dex"]; player.int_=data["int_"]
        player.inventory=data["inventory"]
        player.equipped=data["equipped"]
        player.spells=[dict(s) for s in SPELLS if s["name"] in data.get("spells",[])]
        player.quests=data.get("quests",[dict(q) for q in QUESTS])
        buildings.clear()
        for bd in data.get("buildings",[]):
            buildings.append(Building(bd["type"],bd["tx"],bd["ty"]))
        return True
    except Exception as e:
        print("Load error:",e)
        return False


# ── Main game loop ────────────────────────────────────────────────────────────
def main():
    screen=pygame.display.set_mode((SW,SH))
    pygame.display.set_caption("DemiWorldT")
    clock=pygame.time.Clock()

    state=ST_MENU
    player=None
    camera=Camera()
    enemies=[]; npcs=[]; buildings=[]
    projectiles=[]; floats=[]

    inv_selected=0
    quest_scroll=0
    shop_selected=0
    craft_tab="Fletching"; craft_selected=0
    active_npc=None; dial_idx=0
    place_type="House"
    pause_btns={}; main_btns={}; class_btns={}
    msg_queue=[]  # [(text,timer)]
    atk_cd=0.0
    spell_idx=0
    last_resource_tick=0.0

    def add_msg(text, col=WHITE):
        msg_queue.append([text, 180, col])

    def respawn():
        nonlocal state
        player.hp=player.max_hp//2
        player.mp=player.max_mp//2
        player.sta=50
        player.x=50*TILE; player.y=50*TILE
        state=ST_PLAY

    def harvest_nearby():
        tx=player.tile_x; ty=player.tile_y
        btype=WORLD_MAP[ty][tx] if 0<=ty<MAP_H and 0<=tx<MAP_W else "plains"
        if btype=="wood_area":
            player.add_item("wood",2); add_msg("+2 Wood",GREEN)
        elif btype=="mine":
            player.add_item("iron ore",1); add_msg("+1 Iron Ore",GRAY)
            if random.random()<0.1: player.add_item("magic crystal",1); add_msg("+1 Magic Crystal!",PURPLE)
        elif btype=="plains":
            if random.random()<0.4: player.add_item("herb",1); add_msg("+1 Herb",GREEN)
        elif btype=="mountain":
            player.add_item("stone",2); add_msg("+2 Stone",LTGRAY)

    dt=0.0
    running=True

    while running:
        dt=clock.tick(FPS)/1000.0
        mx,my=pygame.mouse.get_pos()
        mouse_clicked=False
        keys=pygame.key.get_pressed()

        for ev in pygame.event.get():
            if ev.type==pygame.QUIT:
                running=False

            elif ev.type==pygame.MOUSEBUTTONDOWN and ev.button==1:
                mouse_clicked=True

            elif ev.type==pygame.KEYDOWN:
                if state==ST_MENU:
                    pass
                elif state==ST_PLAY:
                    if ev.key==pygame.K_ESCAPE: state=ST_PAUSE
                    elif ev.key==pygame.K_i: state=ST_INV
                    elif ev.key==pygame.K_q: state=ST_QUEST
                    elif ev.key==pygame.K_c: player.crouching=not player.crouching
                    elif ev.key==pygame.K_b: state=ST_CITY
                    elif ev.key==pygame.K_e:
                        # Interact: find nearest NPC
                        best=None; best_d=80
                        for n in npcs:
                            d=math.hypot(n.x-player.x,n.y-player.y)
                            if d<best_d: best=n; best_d=d
                        if best:
                            active_npc=best; dial_idx=0; state=ST_DIAL
                            if best.job in("Merchant","Blacksmith"):
                                state=ST_SHOP
                        else:
                            harvest_nearby()
                    elif ev.key==pygame.K_F5:
                        save_game(player,buildings); add_msg("Game Saved!",GREEN)
                    elif ev.key==pygame.K_F9:
                        if load_game(player,buildings): add_msg("Game Loaded!",CYAN)
                        else: add_msg("No save found.",RED)
                    elif ev.key==pygame.K_TAB:
                        if player.spells:
                            spell_idx=(spell_idx+1)%len(player.spells)
                            add_msg(f"Spell: {player.spells[spell_idx]['name']}",PURPLE)
                    elif ev.key==pygame.K_m: state=ST_MAP

                elif state==ST_PAUSE:
                    if ev.key==pygame.K_ESCAPE: state=ST_PLAY
                elif state in(ST_INV,ST_QUEST,ST_SHOP,ST_CRAFT,ST_DIAL,ST_CITY,ST_MAP):
                    if ev.key==pygame.K_ESCAPE: state=ST_PLAY
                elif state==ST_GAMEOVER:
                    if ev.key==pygame.K_r: respawn()
                    elif ev.key==pygame.K_m: state=ST_MENU

        # ── State: MENU ──────────────────────────────────────────────────────
        if state==ST_MENU:
            screen.fill(BLACK)
            main_btns=draw_main_menu(screen)
            if mouse_clicked:
                if main_btns.get("New Game") and main_btns["New Game"].collidepoint(mx,my):
                    state=ST_CLASS
                elif main_btns.get("Load Game") and main_btns["Load Game"].collidepoint(mx,my):
                    player=Player("Warrior")
                    enemies,npcs,buildings=spawn_world_entities()
                    camera=Camera()
                    if load_game(player,buildings):
                        state=ST_PLAY; add_msg("Game Loaded!",CYAN)
                    else:
                        add_msg("No save file found.",RED); state=ST_CLASS
                elif main_btns.get("Quit") and main_btns["Quit"].collidepoint(mx,my):
                    running=False

        # ── State: CLASS SELECT ──────────────────────────────────────────────
        elif state==ST_CLASS:
            screen.fill(BLACK)
            class_btns=draw_class_select(screen)
            if mouse_clicked:
                for cname,cbr in class_btns.items():
                    if cbr.collidepoint(mx,my):
                        player=Player(cname)
                        enemies,npcs,buildings=spawn_world_entities()
                        camera=Camera()
                        state=ST_PLAY
                        add_msg(f"Welcome, {cname}! WASD=move, E=interact, I=inventory",GOLD)

        # ── State: PLAY ──────────────────────────────────────────────────────
        elif state==ST_PLAY:
            # Movement
            spd=player.speed*(1.5 if keys[pygame.K_LSHIFT] and player.sta>5 else 1.0)
            if player.crouching: spd*=0.5
            if keys[pygame.K_LSHIFT] and player.sta>5 and (keys[pygame.K_w] or keys[pygame.K_s] or keys[pygame.K_a] or keys[pygame.K_d]):
                player.sta=max(0,player.sta-20*dt)
            mx2=int(player.x//TILE); my2=int(player.y//TILE)
            if keys[pygame.K_w]:
                ny=player.y-spd*dt*60
                nty=int(ny//TILE)
                if 0<=nty<MAP_H and WORLD_MAP[nty][mx2]!="water": player.y=ny
            if keys[pygame.K_s]:
                ny=player.y+spd*dt*60
                nty=int(ny//TILE)
                if 0<=nty<MAP_H and WORLD_MAP[nty][mx2]!="water": player.y=ny
            if keys[pygame.K_a]:
                nx=player.x-spd*dt*60
                ntx=int(nx//TILE)
                if 0<=ntx<MAP_W and WORLD_MAP[my2][ntx]!="water": player.x=nx
            if keys[pygame.K_d]:
                nx=player.x+spd*dt*60
                ntx=int(nx//TILE)
                if 0<=ntx<MAP_W and WORLD_MAP[my2][ntx]!="water": player.x=nx
            # Clamp
            player.x=max(TILE,min(player.x,(MAP_W-1)*TILE))
            player.y=max(TILE,min(player.y,(MAP_H-1)*TILE))

            # Attack (left click)
            atk_cd=max(0,atk_cd-dt)
            if mouse_clicked and atk_cd<=0:
                wx=mx+camera.x; wy=my+camera.y
                # Ranged/magic: fire projectile
                w=None
                if player.equipped["weapon"]:
                    w=next((ww for ww in WEAPONS if ww["name"]==player.equipped["weapon"]),None)
                if w and w["type"] in("ranged","magic"):
                    col=ORANGE if w["type"]=="ranged" else PURPLE
                    projectiles.append(Projectile(player.x,player.y,wx,wy,player.atk_power(),col))
                    atk_cd=0.6
                else:
                    # Melee: hit closest enemy
                    for e in enemies:
                        if math.hypot(e.x-player.x,e.y-player.y)<80:
                            dmg=max(1,player.atk_power()-e.defense+random.randint(-3,3))
                            e.hp-=dmg
                            floats.append(FloatText(f"-{dmg}",e.x,e.y,RED))
                            atk_cd=0.5
                            # Spell cast (right click logic here: just melee for now)
                            break

            # Spell cast (right click)
            if pygame.mouse.get_pressed()[2] and player.spells:
                sp=player.spells[spell_idx]
                if player.mp>=sp["mp"] and atk_cd<=0:
                    player.mp-=sp["mp"]
                    wx2=mx+camera.x; wy2=my+camera.y
                    if sp["dmg"]<0:  # Heal
                        player.hp=min(player.max_hp, player.hp-sp["dmg"])
                        floats.append(FloatText(f"+{-sp['dmg']} HP",player.x,player.y-20,GREEN))
                    elif sp["dmg"]>0:
                        projectiles.append(Projectile(player.x,player.y,wx2,wy2,sp["dmg"],sp["col"],10))
                    floats.append(FloatText(sp["name"],player.x,player.y-40,sp["col"]))
                    atk_cd=0.8

            # Update enemies
            dead_enemies=[]
            for e in enemies:
                e.update(player,dt)
                # Enemy hits player
                if math.hypot(e.x-player.x,e.y-player.y)<28:
                    if e.atk_cd<=0:
                        dmg=max(1,e.atk-player.def_power()+random.randint(-2,2))
                        player.hp-=dmg
                        floats.append(FloatText(f"-{dmg}",player.x,player.y-30,RED))
                        e.atk_cd=1.2
                if e.hp<=0:
                    dead_enemies.append(e)
            for e in dead_enemies:
                enemies.remove(e)
                lvlup=player.gain_xp(e.xp_val)
                floats.append(FloatText(f"+{e.xp_val} XP",e.x,e.y,YELLOW))
                if e.loot:
                    player.add_item(e.loot,1)
                    floats.append(FloatText(f"+{e.loot}",e.x,e.y-20,GREEN))
                if lvlup:
                    add_msg(f"LEVEL UP! Now level {player.level}!",GOLD)
                # Quest kill progress
                for q in player.quests:
                    if not q["done"] and q["target"]==e.name:
                        q["prog"]=min(q["prog"]+1,q["need"])
                        if q["prog"]>=q["need"]:
                            q["done"]=True
                            player.gold+=q["reward_gold"]
                            player.gain_xp(q["reward_xp"])
                            add_msg(f"Quest done: {q['name']}! +{q['reward_gold']}g",GOLD)
                # Faction rep
                if e.faction=="bandit": player.faction_rep["kingdom"]["rep"]+=1
                elif e.faction=="goblin": player.faction_rep["kingdom"]["rep"]+=1

            # Update projectiles
            for p in projectiles[:]:
                p.update()
                if not p.alive:
                    projectiles.remove(p); continue
                for e in enemies:
                    if math.hypot(p.x-e.x,p.y-e.y)<20:
                        dmg=max(1,p.dmg-e.defense+random.randint(-2,2))
                        e.hp-=dmg
                        floats.append(FloatText(f"-{dmg}",e.x,e.y,RED))
                        p.alive=False
                        if e.hp<=0:
                            dead_enemies.append(e)
                        break

            # Update floats
            for f2 in floats[:]:
                f2.update()
                if f2.life<=0: floats.remove(f2)

            # Player regen
            player.regen(dt)

            # Automation: auto-harvest near resource areas every 5s
            last_resource_tick+=dt
            if last_resource_tick>5.0:
                last_resource_tick=0
                for bld in buildings:
                    if bld.btype=="Farm":
                        player.add_item("herb",1)
                    elif bld.btype=="Warehouse":
                        player.add_item("stone",1)

            # Death
            if player.hp<=0:
                state=ST_GAMEOVER

            # Camera
            camera.update(player)

            # DRAW
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            for bld in buildings: bld.draw(screen,camera.x,camera.y)
            for e in enemies: e.draw(screen,camera.x,camera.y)
            for n in npcs: n.draw(screen,camera.x,camera.y)
            for p in projectiles: p.draw(screen,camera.x,camera.y)
            for f2 in floats: f2.draw(screen,camera.x,camera.y)
            player.draw(screen,camera.x,camera.y)
            draw_hud(screen,player)
            draw_minimap(screen,player,enemies)

            # Current spell HUD
            if player.spells:
                sp=player.spells[spell_idx]
                txt(screen,f"Spell [{spell_idx+1}]: {sp['name']} ({sp['mp']}mp)",10,10,13,sp["col"])
                txt(screen,"TAB=next spell  RClick=cast",10,26,11,GRAY)

            # Biome label
            btype=WORLD_MAP[player.tile_y][player.tile_x] if 0<=player.tile_y<MAP_H and 0<=player.tile_x<MAP_W else "?"
            txt(screen,btype.upper(),SW//2,10,13,LTGRAY,center=True)

            # Message log
            for i,m in enumerate(msg_queue):
                txt(screen,m[0],SW//2,SH//2-160-i*22,15,m[2],center=True)
                m[1]-=1
            msg_queue[:]=[[t,ti,c] for t,ti,c in msg_queue if ti>0]

        # ── State: INVENTORY ─────────────────────────────────────────────────
        elif state==ST_INV:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            draw_hud(screen,player)
            xbtn,ibtn,eq_btn,dr_btn=draw_inventory(screen,player,inv_selected)
            items=list(player.inventory.items())
            if mouse_clicked:
                if xbtn.collidepoint(mx,my): state=ST_PLAY
                for idx,(sx,sy,sw2,sh2) in ibtn.items():
                    if pygame.Rect(sx,sy,sw2,sh2).collidepoint(mx,my):
                        inv_selected=idx
                if eq_btn and eq_btn.collidepoint(mx,my) and 0<=inv_selected<len(items):
                    name,_=items[inv_selected]
                    # Equip weapon or armor
                    wm=next((w for w in WEAPONS if w["name"]==name),None)
                    am=next((p for aset in ARMOR_SETS for p in aset["parts"] if p==name),None)
                    if wm: player.equipped["weapon"]=name; add_msg(f"Equipped {name}",GREEN)
                    elif am: player.equipped["armor"]=name; add_msg(f"Equipped {name}",GREEN)
                    # Use potion
                    elif "Potion" in name:
                        if "Health" in name: player.hp=min(player.max_hp,player.hp+50); add_msg("+50 HP",GREEN)
                        elif "Mana" in name: player.mp=min(player.max_mp,player.mp+50); add_msg("+50 MP",BLUE)
                        player.inventory[name]-=1
                        if player.inventory[name]<=0: del player.inventory[name]; inv_selected=0
                if dr_btn and dr_btn.collidepoint(mx,my) and 0<=inv_selected<len(items):
                    name,_=items[inv_selected]
                    player.inventory[name]-=1
                    if player.inventory[name]<=0: del player.inventory[name]; inv_selected=0
                    add_msg(f"Dropped {name}",GRAY)

        # ── State: QUESTS ────────────────────────────────────────────────────
        elif state==ST_QUEST:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            xbtn=draw_quest_log(screen,player)
            if mouse_clicked and xbtn.collidepoint(mx,my): state=ST_PLAY

        # ── State: DIALOGUE ──────────────────────────────────────────────────
        elif state==ST_DIAL:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            draw_hud(screen,player)
            if active_npc:
                xbtn,opt_btns=draw_dialogue(screen,active_npc,dial_idx)
                if mouse_clicked:
                    if xbtn.collidepoint(mx,my): state=ST_PLAY
                    for i,(br,opt) in opt_btns.items():
                        if br.collidepoint(mx,my):
                            if opt=="Goodbye": state=ST_PLAY
                            elif opt=="Browse shop": state=ST_SHOP
                            else: dial_idx=min(dial_idx+1,len(active_npc.dialogue)-1)

        # ── State: SHOP ──────────────────────────────────────────────────────
        elif state==ST_SHOP:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            if active_npc:
                xbtn,shop_btns,items=draw_shop(screen,active_npc,player,shop_selected)
                if mouse_clicked:
                    if xbtn.collidepoint(mx,my): state=ST_PLAY
                    for i,sbr in shop_btns.items():
                        if sbr.collidepoint(mx,my) and i<len(items):
                            name,info=items[i]
                            if player.gold>=info["price"] and info["qty"]>0:
                                player.gold-=info["price"]
                                player.add_item(name,1)
                                info["qty"]-=1
                                add_msg(f"Bought {name}!",GREEN)
                            else:
                                add_msg("Not enough gold or out of stock.",RED)

        # ── State: CRAFT ─────────────────────────────────────────────────────
        elif state==ST_CRAFT:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            xbtn,tab_btns,craft_btns=draw_crafting(screen,player,craft_tab,craft_selected)
            if mouse_clicked:
                if xbtn.collidepoint(mx,my): state=ST_PLAY
                for tab,tbr in tab_btns.items():
                    if tbr.collidepoint(mx,my): craft_tab=tab; craft_selected=0
                for i,(cbtn,recipe) in craft_btns.items():
                    if cbtn.collidepoint(mx,my):
                        can=all(player.inventory.get(n,0)>=q for n,q in recipe["cost"].items())
                        if can:
                            for n,q in recipe["cost"].items():
                                player.inventory[n]=player.inventory.get(n,0)-q
                                if player.inventory[n]<=0: del player.inventory[n]
                            for n,q in recipe["out"].items():
                                player.add_item(n,q)
                            add_msg(f"Crafted: {recipe['name']}!",GREEN)
                        else:
                            add_msg("Not enough materials.",RED)

        # ── State: PAUSE ─────────────────────────────────────────────────────
        elif state==ST_PAUSE:
            # Draw game world behind
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            draw_hud(screen,player)
            # Darken
            ov=pygame.Surface((SW,SH),pygame.SRCALPHA); ov.fill((0,0,20,160)); screen.blit(ov,(0,0))
            xbtn,pause_btns=draw_pause(screen)
            if mouse_clicked:
                if xbtn.collidepoint(mx,my): state=ST_PLAY
                if pause_btns.get("Resume","") and isinstance(pause_btns["Resume"],pygame.Rect) and pause_btns["Resume"].collidepoint(mx,my): state=ST_PLAY
                if pause_btns.get("Save Game","") and isinstance(pause_btns["Save Game"],pygame.Rect) and pause_btns["Save Game"].collidepoint(mx,my):
                    save_game(player,buildings); add_msg("Saved!",GREEN); state=ST_PLAY
                if pause_btns.get("Load Game","") and isinstance(pause_btns["Load Game"],pygame.Rect) and pause_btns["Load Game"].collidepoint(mx,my):
                    load_game(player,buildings); state=ST_PLAY
                if pause_btns.get("Main Menu","") and isinstance(pause_btns["Main Menu"],pygame.Rect) and pause_btns["Main Menu"].collidepoint(mx,my): state=ST_MENU
                if pause_btns.get("Quit","") and isinstance(pause_btns["Quit"],pygame.Rect) and pause_btns["Quit"].collidepoint(mx,my): running=False

        # ── State: CITY BUILD ────────────────────────────────────────────────
        elif state==ST_CITY:
            screen.fill(BLACK)
            draw_world(screen,camera.x,camera.y)
            for bld in buildings: bld.draw(screen,camera.x,camera.y)
            draw_hud(screen,player)
            xbtn,type_btns=draw_city_build(screen,player,buildings,place_type)
            if mouse_clicked:
                if xbtn.collidepoint(mx,my): state=ST_PLAY
                for bt,tbr in type_btns.items():
                    if tbr.collidepoint(mx,my): place_type=bt
                # Place on map (outside panel)
                if mx>280:
                    cost=Building.TYPES[place_type]["cost"]
                    can=all(player.inventory.get(n,0)>=q for n,q in cost.items() if q>0)
                    if can:
                        tx2=int((mx+camera.x)//TILE); ty2=int((my+camera.y)//TILE)
                        buildings.append(Building(place_type,tx2,ty2))
                        for n,q in cost.items():
                            if q>0:
                                player.inventory[n]=player.inventory.get(n,0)-q
                                if player.inventory[n]<=0: del player.inventory[n]
                        add_msg(f"Built {place_type}!",GREEN)
                    else:
                        add_msg("Not enough materials!",RED)

        # ── State: MAP ───────────────────────────────────────────────────────
        elif state==ST_MAP:
            screen.fill((10,10,30))
            xbtn=draw_panel(screen,40,40,SW-80,SH-80,"World Map")
            MW=SW-120; MH=SH-120
            scale_x=MW/MAP_W; scale_y=MH/MAP_H
            for ty in range(0,MAP_H,2):
                for tx in range(0,MAP_W,2):
                    col=BIOME_COL.get(WORLD_MAP[ty][tx],(80,80,80))
                    screen.set_at((60+int(tx*scale_x),60+int(ty*scale_y)),col)
            # Labels
            for tx,ty,name in TOWNS:
                sx=60+int(tx*scale_x); sy=60+int(ty*scale_y)
                pygame.draw.circle(screen,YELLOW,(sx,sy),4)
                txt(screen,name,sx+5,sy-8,11,YELLOW)
            for cx2,cy2,name in CITIES:
                sx=60+int(cx2*scale_x); sy=60+int(cy2*scale_y)
                pygame.draw.circle(screen,GOLD,(sx,sy),6)
                txt(screen,name,sx+7,sy-8,12,GOLD)
            # Player dot
            px=60+int(player.tile_x*scale_x); py=60+int(player.tile_y*scale_y)
            pygame.draw.circle(screen,WHITE,(px,py),5)
            txt(screen,"● You",px+6,py-6,11,WHITE)
            if mouse_clicked and xbtn.collidepoint(mx,my): state=ST_PLAY

        # ── State: GAME OVER ─────────────────────────────────────────────────
        elif state==ST_GAMEOVER:
            draw_gameover(screen)

        # Open crafting with K
        if state==ST_PLAY and pygame.key.get_pressed()[pygame.K_k]:
            state=ST_CRAFT

        pygame.display.flip()

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()